dataset:
  batch_size: 4
  dataset_path: Data/climate_2014_2023_final.csv
  dataset: climate
  date_template: '{timestep}_{index}_date'
  hf_repo: Howard881010/climate-2day-inContext
  input_window: 2
  instruction_template: 'Given the weather information of the first {input_window}
    {timestep}, predict the weather information of the next {output_window} {timestep}.
    Output the result strictly in the following JSON format and no additional text:
    '
  model_type: text_text
  name: climate
  numerical_columns:
  - temp
  output_window: 2
  repo: Howard881010/climate-7day-mixed
  text_template: '{timestep}_{index}_weather_forecast'
  time_template: '{timestep}_{index}_{col}'
  timestep: day
  num_key_name: temp
  text_key_name: weather_forecast
  # 1 for text2text, 2 for textTime2textTime, 3 for textTime2text, 4 for textTime2time
  case: 1
  train_split: 0.8
  valid_split: 0.9
  split: test
  seed: 42